### ISSUE TITLE
Post hails return "Taxi is not available" after a failure

### ISSUE THREAD

**Issue by supmob1** [openmaraude/APITaxi#225]
1 - We post a hails to our endpoint
2 - Our endpoint raise an error (taxis do not even receive the hails) , so hails status is set to 'failure' by ODT
3 - We post the same hails to our endpoint, ODT reply "Taxi is not available"

Here is the POST hails
{
  "data": [
   {
  "customer_address": "63,Rue des Rancy,Rhône",
  "customer_id": "mob1Taxi-0-c62f3bce-146d-4366-ab9d-8c747b105755",
  "customer_lat": "45.756501",
  "customer_lon": "4.856979",
  "customer_phone_number": "+33 662265",
  "operateur": "mob1taxi",
  "taxi_id": "03013dbb-5df2-4f51-8876-06028447aaef"
}
  ]
}

4 - We checked the taxi status doing a GET/{taxis_id} it return status:answering
{
  "data": [
    {
      "status": "answering",
      "ads": {
        "insee": "69123",
        "numero": "1076"
      },
      "driver": {
        "departement": "69",
        "professional_licence": "000245"
      },
      "last_update": 1440628986,
      "crowfly_distance": null,
      "vehicle": {
        "color": null,
        "characteristics": null,
        "nb_seats": null,
        "constructor": null,
        "model": "bmw",
        "licence_plate": "999-xxx-999"
      },
      "operator": "mob1taxi",
      "position": {
        "lat": null,
        "lon": null
      },
      "id": "03013dbb-5df2-4f51-8876-06028447aaef"
    }
  ]
}

Could u check on your side please ?

**Comment by odtvince** [comment]
That is indeed the intended behaviour.

When the we relay your hail from you as a Search Engine to you as an Operator, we set the status of the "Taxi" object to "answering" in order to avoid anyone to try and hail the same taxi while he is answering your request.

Then, when you as an Operator raise an error, we set the status of the "Hail" object to "failure" and we DON'T set the status of the "Taxi" object back to "free": there seem to be a problem with hailing that taxi, so we don't want to automaticaly put it back in the pool of taxis which can be hailed by clients.

If you try to see the taxis available around this position at that point in time (via GET /taxis/), you will NOT see that taxi anymore, because its status is not "free" and it is thus not hailable.

In order to be able to hail that taxi again, after you've fixed the problem, you have to set the status of the "Taxi" object to "free" via a PUT on /taxis/{taxi_id}. You will then see that taxi again via GET /taxis/ and be able to hail it via POST /hails/.

Hope this helps.

**Comment by supmob1** [comment]
I think this will be an issue for real search engine and on the field :
- assuming that the phone number or any information is incomplete, our endpoint checks and validate input before transmitting to our dispatch server. So we return "failure" not because of a taxi dispatch problem, but rather for an incorrect payload. Taxi is still free, so it means, that you will block the taxi.
- We can imagine, a search engine, sending incorrect payload, so this will make all taxi from one company not available !

We already block the taxi status on our side, when our dispatching is going to propose the hails to driver by setting a PUT status:"answering", because we know exactly when we send the payload to driver. So, if there is another search engine that is going at the same time to hails the same taxi, our endpoint will reply to ODT "taxi_not_available" or ODT will have the information already from the operator (via the PUT done previously).

**Comment by odtvince** [comment]
Incomplete hail payloads sent by Search Engine should be refused on our side, so you should never see them arriving on your Operator endpoint. Some of those tests still leave to be desired on our side (like the one for the customer_phone_number) but it is definitely high on our todo list. It is nevertheless a good thing for your implementation to handle them graciously (i.e. send back a failure answer to the hail request and PUT the taxi back to "free" status).

There are 4 main reasons for you as an operator to send us a failure on a hail:
* because the taxi just signed off
* because the taxi was just hailed by a non-ODT customer (street client or through your app)
* because there is a technical problem on your system
* because the request you received was malformed (which should not happen anymore when we're finished improving the tests on our side)
We leave the taxi as unavailable by default because it is the right thing to do for the 3 former cases. If you encounter the latter case, you can still PUT the taxi back in "free" status immediately after you send the failure response to the hail.


As a side note, as an operator receiving a hail request you don't need to change the taxi status from "free" to "answering" because we have already done it when we send you the hail request. The earlier the better in order to avoid race conditions. We will improve the documentation to make that fact clear.
